name: ${project.name}
version: ${project.version}
author: DarkBlade12
website: ${project.url}
softdepend: [Vault, Multiverse-Core, Multiworld, PlotMe, MyWorlds, Essentials]

main: com.darkblade12.itemslotmachine.ItemSlotMachine

commands:
 design:
  description: Commands related to designs
  usage: /<command> help
  aliases: [sdesign, slotdesign]
 coin:
  description: Commands related to coins
  usage: /<command> help
  aliases: [scoin, slotcoin]
 slot:
  description: Commands related to slot machines
  usage: /<command> help
  aliases: [smachine, slotmachine]
 statistic:
  description: Commands related to statistics
  usage: /<command> help
  aliases: [sstatistic, slotstatistic]